version: '2.1'

services:
  redis:
      image: redis:7
      ports:
        - "6379:6379"
  # web:
  #   build: .
  #   command: python3 manage.py runserver 0.0.0.0:8001 
  #   volumes:
  #     - '.:/src'
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     crm_db:
  #       condition: service_healthy
  #   links:
  #     - crm_db
  