# Generated by Django 3.0.4 on 2022-07-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20220702_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pic',
            field=models.ForeignKey(db_column='pic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
