# Generated by Django 3.0.4 on 2022-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220703_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawldata',
            name='post_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crawldata',
            name='post_picture',
            field=models.TextField(default=''),
        ),
    ]
