# Generated by Django 3.0.4 on 2022-07-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220705_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datachannel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='color',
        ),
    ]
