# Generated by Django 3.0.4 on 2022-07-14 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220710_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='crawl_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CrawlData'),
        ),
        migrations.AlterField(
            model_name='datachannel',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_channels', to='api.DataSource'),
        ),
        migrations.AlterField(
            model_name='datasubstatus',
            name='data_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sub_status', to='api.DataStatus'),
        ),
    ]
