# Generated by Django 3.0.4 on 2022-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220715_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
