# Generated by Django 3.0.4 on 2022-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_role_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view', 'View'), ('change', 'Change'))},
        ),
    ]
