# Generated by Django 3.0.4 on 2022-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fbpage_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='picture_url',
            field=models.TextField(default=''),
        ),
    ]
