# Generated by Django 3.0.4 on 2022-07-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fbuser_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderdetailhistory',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='discount_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='discount_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='discount_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='discount_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='crawl_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CrawlData'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='discount_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='discount_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('value', models.BigIntegerField()),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='api.Order')),
            ],
            options={
                'db_table': 'payments',
                'index_together': {('company', 'status', 'deleted_at'), ('company', 'type', 'deleted_at'), ('company', 'order', 'deleted_at')},
            },
        ),
    ]
