# Generated by Django 3.0.4 on 2022-04-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220411_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('page_name', models.CharField(max_length=1024)),
                ('access_token', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'fb_pages',
            },
        ),
        migrations.CreateModel(
            name='FBPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post_id', models.CharField(db_index=True, max_length=64)),
                ('post_created_time', models.DateTimeField(db_index=True)),
                ('permalink_url', models.CharField(max_length=1024)),
                ('message', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FBPage')),
            ],
            options={
                'db_table': 'fb_posts',
                'unique_together': {('page_id', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='FBComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment_id', models.CharField(db_index=True, max_length=64)),
                ('comment_created_time', models.DateTimeField()),
                ('username', models.CharField(max_length=1024)),
                ('user_id', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('phone', models.CharField(default='', max_length=64)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FBPost')),
            ],
            options={
                'db_table': 'fb_comments',
            },
        ),
    ]
