# Generated by Django 3.0.4 on 2022-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220719_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsyntax',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
