# Generated by Django 3.0.4 on 2022-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fbcomment_fbpage_fbpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbcomment',
            name='phone',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
