# Generated by Django 3.0.4 on 2022-04-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220417_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(max_length=1024)),
                ('user_id', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('phone', models.CharField(default='', max_length=64, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FBPage')),
            ],
            options={
                'db_table': 'fb_messages',
            },
        ),
    ]
