# Generated by Django 3.0.4 on 2022-07-30 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20220727_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='annual_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='annual_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='accountant_note',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approver',
            field=models.ForeignKey(db_column='approver_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_note',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
