# Generated by Django 3.0.4 on 2022-04-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_fbmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('charge_by', models.CharField(max_length=128)),
                ('payment_method', models.CharField(max_length=128)),
                ('payment_date', models.DateField()),
                ('payment_notify', models.DateField()),
                ('agent_fee', models.FloatField()),
                ('minute_fee', models.TextField(max_length=1024)),
                ('external_fee', models.FloatField()),
                ('sip_fee_calculation', models.CharField(max_length=128)),
                ('call_center_user', models.CharField(max_length=256)),
                ('call_center_password', models.CharField(max_length=1024)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', unique=True)),
            ],
            options={
                'db_table': 'call_center',
            },
        ),
        migrations.CreateModel(
            name='CallAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('secret', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_agent',
            },
        ),
    ]
