# Generated by Django 3.0.4 on 2022-07-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220727_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='care_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='care_notes',
            field=models.TextField(default=''),
        ),
    ]
