# Generated by Django 3.0.4 on 2022-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_callagent_callcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenter',
            name='payment_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='payment_notify',
            field=models.IntegerField(),
        ),
    ]
