# Generated by Django 3.0.4 on 2022-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220730_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_no',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
