# Generated by Django 3.0.4 on 2022-07-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220729_1148'),
        ('api', '0015_payment_invoice_no'),
    ]

    operations = [
    ]
