# Generated by Django 3.0.4 on 2022-04-28 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sipserviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='callagent',
            name='sip_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcenter',
            name='discount_type',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcenter',
            name='discount_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcenter',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sipserviceinfo',
            name='sip_company_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
