# Generated by Django 3.0.4 on 2022-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20220730_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='total_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
