# Generated by Django 3.0.4 on 2022-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220428_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenter',
            name='discount_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
    ]
