# Generated by Django 3.0.4 on 2022-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220730_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='duplicated_with',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='duplicated_with',
            field=models.IntegerField(null=True),
        ),
    ]
