# Generated by Django 3.0.4 on 2022-04-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220428_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('use_from', models.DateField()),
                ('use_to', models.DateField()),
                ('charge_from', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'agent_register',
            },
        ),
    ]
