# Generated by Django 3.0.4 on 2022-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220731_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='confirmed_date',
            field=models.DateField(null=True),
        ),
    ]
