# Generated by Django 3.0.4 on 2022-04-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agentregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentregister',
            old_name='company_id',
            new_name='company',
        ),
    ]
