# Generated by Django 3.0.4 on 2022-08-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_orderhistory_confirmed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualorder',
            name='order_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_approval_annual_debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_approval_debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnnualOrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('annual_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AnnualOrder')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail')),
            ],
            options={
                'db_table': 'annual_order_histories',
            },
        ),
    ]
