# Generated by Django 3.0.4 on 2022-04-28 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220428_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentregister',
            name='charge_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
