# Generated by Django 3.0.4 on 2022-08-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220813_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualorder',
            name='order',
        ),
    ]
