# Generated by Django 3.0.4 on 2022-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_annualorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='annual_paid_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='annual_remaining_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='annual_paid_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='annual_remaining_payment_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
