# Generated by Django 3.0.4 on 2022-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220429_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='access_token',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='expire_time',
            field=models.IntegerField(default=0),
        ),
    ]
