# Generated by Django 3.0.4 on 2022-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220815_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='last_message_check_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fbpage',
            name='last_page_check_time',
            field=models.DateTimeField(null=True),
        ),
    ]
