# Generated by Django 3.0.4 on 2022-08-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220819_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbpage',
            old_name='last_page_check_time',
            new_name='last_post_check_time',
        ),
    ]
