# Generated by Django 3.0.4 on 2022-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220429_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='uid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
