# Generated by Django 3.0.4 on 2022-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220429_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='expire_time',
            field=models.IntegerField(default=0),
        ),
    ]
