# Generated by Django 3.0.4 on 2022-04-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fbpage_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbpage',
            old_name='uid',
            new_name='user',
        ),
    ]
