# Generated by Django 3.0.4 on 2022-08-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrderRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', unique=True)),
            ],
            options={
                'db_table': 'import_order_records',
            },
        ),
    ]
