# Generated by Django 3.0.4 on 2022-04-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220429_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('fb', 'fb'), ('zalo', 'zalo')], db_index=True, default='fb', max_length=64)),
                ('uid', models.CharField(db_index=True, default='', max_length=64)),
                ('username', models.CharField(default='', max_length=1024)),
                ('phone', models.CharField(default='', max_length=64)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('init', 'init')], db_index=True, default='init', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
