# Generated by Django 3.0.4 on 2022-08-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_importorderrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderrecords',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
