# Generated by Django 3.0.4 on 2022-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_crawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawdata',
            name='ref_link',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
