# Generated by Django 3.0.4 on 2022-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer_address',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
