# Generated by Django 3.0.4 on 2022-04-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_crawdata_ref_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='last_check_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fbpost',
            name='last_check_time',
            field=models.IntegerField(default=True),
        ),
    ]
