# Generated by Django 3.0.4 on 2022-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220823_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='datastatus',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='datastatus',
            unique_together={('name', 'company')},
        ),
    ]
