# Generated by Django 3.0.4 on 2022-04-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220430_0955'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawdata',
            table='craw_data',
        ),
    ]
