# Generated by Django 3.0.4 on 2022-04-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220430_1001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawdata',
            table='crawl_data',
        ),
    ]
