# Generated by Django 3.0.4 on 2022-08-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220831_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='uid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='fbuser',
            unique_together={('uid', 'company')},
        ),
    ]
