# Generated by Django 3.0.4 on 2022-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220831_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpage',
            name='page_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='fbpage',
            unique_together={('page_id', 'company')},
        ),
    ]
