# Generated by Django 3.0.4 on 2022-04-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220430_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbcomment',
            name='last_check_time',
            field=models.IntegerField(default=True),
        ),
    ]
