# Generated by Django 3.0.4 on 2022-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220831_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='created_by',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='updated_by',
            field=models.CharField(default='', max_length=64),
        ),
    ]
