# Generated by Django 3.0.4 on 2022-10-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220905_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualorder',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_order', to='api.OrderDetail'),
        ),
    ]
