# Generated by Django 3.0.4 on 2022-04-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220430_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
