# Generated by Django 3.0.4 on 2022-11-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20221018_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='annual_paid_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annualorder',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail'),
        ),
    ]
