# Generated by Django 3.0.4 on 2022-05-02 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_fbpage_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('fb', 'fb'), ('zalo', 'zalo')], db_index=True, default='fb', max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('ref_link', models.CharField(default='', max_length=2048)),
                ('uid', models.CharField(db_index=True, default='', max_length=64)),
                ('username', models.CharField(default='', max_length=1024)),
                ('phone', models.CharField(default='', max_length=64)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('init', 'init')], db_index=True, default='init', max_length=64)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crawl_data',
            },
        ),
        migrations.DeleteModel(
            name='CrawData',
        ),
    ]
