# Generated by Django 3.0.4 on 2022-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fbpage_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenter',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='payment_notify',
            field=models.DateField(),
        ),
    ]
