# Generated by Django 3.0.4 on 2022-05-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220502_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawldata',
            name='type',
            field=models.CharField(choices=[('post', 'post'), ('msg', 'msg')], db_index=True, default='post', max_length=64),
        ),
    ]
