# Generated by Django 3.0.4 on 2022-12-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20221113_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenterpaymenthistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
