# Generated by Django 3.0.4 on 2022-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20221209_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='addition_fee',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='renew_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='addition_fee',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='renew_date',
            field=models.DateField(null=True),
        ),
    ]
