# Generated by Django 3.0.4 on 2022-05-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220430_2239'),
        ('api', '0036_crawldata_type'),
    ]

    operations = [
    ]
