# Generated by Django 3.0.4 on 2022-05-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_merge_20220506_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=64)),
                ('address', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.AddField(
            model_name='fbuser',
            name='need_crawl',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(db_index=True)),
                ('price', models.IntegerField(default=0)),
                ('debt', models.IntegerField(default=0)),
                ('due_date', models.DateField(db_index=True)),
                ('annual_debt', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='CallCenterPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('charge_by', models.CharField(max_length=128)),
                ('payment_method', models.CharField(max_length=128)),
                ('payment_date', models.DateField()),
                ('payment_notify', models.DateField()),
                ('agent_fee', models.FloatField()),
                ('minute_fee', models.TextField(max_length=1024)),
                ('external_fee', models.FloatField()),
                ('sip_fee_calculation', models.CharField(max_length=128)),
                ('call_center_user', models.CharField(max_length=256)),
                ('call_center_password', models.CharField(max_length=1024)),
                ('discount_type', models.CharField(max_length=128, null=True)),
                ('discount_value', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', unique=True)),
            ],
            options={
                'db_table': 'callcenter_payment_history',
            },
        ),
    ]
