# Generated by Django 3.0.4 on 2022-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20221213_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='addition_fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
