# Generated by Django 3.0.4 on 2022-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20221213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='annual_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='annual_debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='annual_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='annual_debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
