# Generated by Django 3.0.4 on 2022-05-15 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0038_auto_20220508_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaloOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('oa_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zalo_oas',
            },
        ),
        migrations.CreateModel(
            name='ZaloMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('phone', models.CharField(default='', max_length=64, null=True)),
                ('oa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ZaloOA')),
            ],
            options={
                'db_table': 'zalo_messages',
            },
        ),
    ]
