# Generated by Django 3.0.4 on 2022-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20221213_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_detail_list',
            field=models.CharField(default='', max_length=512),
        ),
    ]
