# Generated by Django 3.0.4 on 2022-05-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_zalomessage_zalooa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooa',
            name='need_crawl',
            field=models.BooleanField(default=False),
        ),
    ]
