# Generated by Django 3.0.4 on 2022-05-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_zalooa_need_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooa',
            name='access_token',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
