# Generated by Django 3.0.4 on 2022-12-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_payment_order_detail_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_detail_list',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='OrderDetailPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.BigIntegerField(default=0)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment')),
            ],
            options={
                'db_table': 'order_detail_payment',
            },
        ),
    ]
