# Generated by Django 3.0.4 on 2022-12-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20221220_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='waiting_approval_debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='waiting_approval_debt',
            field=models.BigIntegerField(default=0),
        ),
    ]
