# Generated by Django 3.0.4 on 2022-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_zalooa_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('callid', models.CharField(max_length=256)),
                ('calldate', models.DateTimeField()),
                ('extension', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=128)),
                ('recordingfile', models.CharField(max_length=2048)),
                ('is_telco', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'call_log',
            },
        ),
    ]
