# Generated by Django 3.0.4 on 2022-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20221220_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='addition_fee',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='waiting_approval_debt',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
