# Generated by Django 3.0.4 on 2022-05-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_calllog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='recordingfile',
            new_name='recording',
        ),
    ]
