# Generated by Django 3.0.4 on 2022-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220517_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callagent',
            name='sip_id',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='call_center_password',
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='call_center_user',
        ),
        migrations.RemoveField(
            model_name='callcenterpaymenthistory',
            name='call_center_password',
        ),
        migrations.RemoveField(
            model_name='callcenterpaymenthistory',
            name='call_center_user',
        ),
    ]
