# Generated by Django 3.0.4 on 2022-12-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20221220_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailhistory',
            name='waiting_approval_debt',
            field=models.BigIntegerField(null=True),
        ),
    ]
