# Generated by Django 3.0.4 on 2022-05-17 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220517_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='direction',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='callid',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='extension',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
