# Generated by Django 3.0.4 on 2023-01-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_notification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
