# Generated by Django 3.0.4 on 2022-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20220517_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='calldate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='recording',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
