# Generated by Django 3.0.4 on 2023-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20230115_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to='export_data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
