# Generated by Django 3.0.4 on 2022-05-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220517_2259'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='calllog',
            index_together={('extension', 'phone', 'status')},
        ),
    ]
