# Generated by Django 3.0.4 on 2023-03-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_exportorderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='auto_picked_order_details',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RemainingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.BigIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment')),
            ],
            options={
                'db_table': 'remaining_payments',
            },
        ),
    ]
