# Generated by Django 3.0.4 on 2022-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220517_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='chargeable_time',
            field=models.IntegerField(default=0),
        ),
    ]
