# Generated by Django 3.0.4 on 2022-05-23 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_calllog_chargeable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='payment_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcenter',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=128),
        ),
        migrations.AddField(
            model_name='param',
            name='description',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='param',
            name='group',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
