# Generated by Django 3.0.4 on 2023-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20230327_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_change_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
