# Generated by Django 3.0.4 on 2023-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_order_total_change_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_change_amount',
            new_name='change_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='annual_change_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
