# Generated by Django 3.0.4 on 2022-05-24 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20220523_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='payment_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=128),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
