# Generated by Django 3.0.4 on 2022-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20220525_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callcenter',
            old_name='total_payment',
            new_name='credit_payment_amount',
        ),
        migrations.RenameField(
            model_name='callcenterpaymenthistory',
            old_name='total_payment',
            new_name='credit_payment_amount',
        ),
        migrations.AddField(
            model_name='callcenter',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='external_payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='total_payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='external_payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenterpaymenthistory',
            name='total_payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
