# Generated by Django 3.0.4 on 2022-05-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20220525_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='callagent',
            name='agent_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AgentRegister'),
        ),
        migrations.AddField(
            model_name='callagent',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=256),
            preserve_default=False,
        ),
    ]
