# Generated by Django 3.0.4 on 2023-06-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_tokenuserstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenuserstatus',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='tokenuserstatus',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='tokenuserstatus',
            name='last_logout_at',
        ),
        migrations.AddField(
            model_name='tokenuserstatus',
            name='current_token',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
