# Generated by Django 3.0.4 on 2022-06-05 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0052_auto_20220526_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'company_emails',
            },
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', unique=True)),
            ],
            options={
                'db_table': 'company_logos',
            },
        ),
        migrations.CreateModel(
            name='DataChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'data_channels',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'data_status',
            },
        ),
        migrations.CreateModel(
            name='DataSubStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('data_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataStatus')),
            ],
            options={
                'db_table': 'data_substatus',
                'unique_together': {('name', 'data_status', 'company')},
            },
        ),
        migrations.CreateModel(
            name='EmailSyntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('column_name', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'email_syntax',
                'unique_together': {('code', 'company')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=128)),
                ('email_name', models.TextField()),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'email_templates',
                'unique_together': {('code', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateField(db_index=True)),
                ('price', models.IntegerField(default=0)),
                ('debt', models.IntegerField(default=0)),
                ('due_date', models.DateField(db_index=True)),
                ('annual_debt', models.IntegerField(default=0)),
                ('annual_due_date', models.DateField(db_index=True)),
                ('shipping_code', models.CharField(default='', max_length=1024)),
                ('shipping_fee', models.BigIntegerField(default=0)),
                ('debt_status', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('data_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DataChannel')),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DataSource')),
                ('data_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DataStatus')),
                ('data_sub_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DataSubStatus')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('remaining_payment_amount', models.BigIntegerField()),
                ('paid_payment_amount', models.BigIntegerField()),
                ('debt', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('file_attach', models.FileField(upload_to='')),
                ('invoice', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'db_table': 'order_details',
                'index_together': {('order', 'type')},
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='datachannel',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataSource'),
        ),
        migrations.AlterUniqueTogether(
            name='datachannel',
            unique_together={('name', 'data_source', 'company')},
        ),
    ]
