# Generated by Django 3.0.4 on 2023-06-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20230618_0128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokenuserstatus',
            table='token_user_status',
        ),
    ]
