# Generated by Django 3.0.4 on 2023-09-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20230618_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='charge_from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='charge_to_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='MonthlyOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('charged_amount', models.IntegerField(default=0)),
                ('approved_amount', models.IntegerField(default=0)),
                ('waiting_approval_amount', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail')),
            ],
            options={
                'db_table': 'monthly_order_details',
            },
        ),
    ]
