# Generated by Django 3.0.4 on 2023-10-09 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20230910_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='mobiphone',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='package',
            name='other',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='package',
            name='viettel',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='package',
            name='vinaphone',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('company', 'deleted_at')},
        ),
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
