# Generated by Django 3.0.4 on 2023-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20231009_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='param',
            name='group',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='param',
            name='value',
            field=models.CharField(max_length=2048),
        ),
    ]
