# Generated by Django 3.0.4 on 2023-10-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20231010_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='mobiphone',
            new_name='mobifone',
        ),
    ]
