# Generated by Django 3.0.4 on 2023-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20231010_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='deposit_warning_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
