# Generated by Django 4.2.9 on 2024-01-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_exportcalllogshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='last_report_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CallCenterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('credit_payment_amount', models.IntegerField(default=0)),
                ('external_payment_amount', models.IntegerField(default=0)),
                ('total_payment_amount', models.IntegerField(default=0)),
                ('current_prices', models.IntegerField(default=0)),
                ('current_minutes', models.IntegerField(default=0)),
                ('call_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.callcenter')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'call_center_reports',
            },
        ),
    ]
