# Generated by Django 4.2.9 on 2024-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_callcenter_last_report_time_callcenterreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenter',
            name='trial_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callcenter',
            name='trial_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calllog',
            name='provider',
            field=models.CharField(default='', max_length=128),
        ),
    ]
