# Generated by Django 4.2.9 on 2024-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_callcenter_trial_expired_callcenter_trial_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='accountcode',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='calllog',
            name='billsec',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='dstchannel',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ip',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='calllog',
            name='userfield',
            field=models.CharField(default='', max_length=128),
        ),
    ]
