# Generated by Django 4.2.9 on 2024-03-17 18:25

import api.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_calllog_accountcode_calllog_billsec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('choose_by_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'legals',
            },
        ),
        migrations.CreateModel(
            name='MainPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('choose_by_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'main_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pickup_date', models.DateField()),
                ('brand', models.CharField(default='', max_length=512)),
                ('lock_provider', models.CharField(default='', max_length=512)),
                ('lock_count', models.IntegerField(default=0)),
                ('phone_number_avg_age', models.FloatField(default=0)),
                ('cancel_date', models.DateField(null=True)),
                ('init_fee', models.FloatField(default=0)),
                ('operate_fee', models.FloatField(default=0)),
                ('open_fee', models.FloatField(default=0)),
                ('other_fee', models.FloatField(default=0)),
                ('init_payment_date', models.DateField(null=True)),
                ('open_payment_date', models.DateField(null=True)),
                ('operate_payment_date', models.DateField(null=True)),
                ('other_payment_date', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.legal')),
                ('main_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainphonenumber')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
            bases=(models.Model, api.models.base.ModelDiffMixin),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('choose_by_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('choose_by_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'phone_number_status',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberMonthlyFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('on_net_fee', models.FloatField(default=0)),
                ('off_net_fee', models.FloatField(default=0)),
                ('billing_month', models.DateField()),
                ('payment_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
            ],
            options={
                'db_table': 'phone_number_monthly_fees',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberLockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checking_lock_date', models.DateField()),
                ('confirm_lock_date', models.DateField(null=True)),
                ('unlock_lock_date', models.DateField(null=True)),
                ('cancel_date', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
            ],
            options={
                'db_table': 'phone_number_lock_histories',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('index', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('choose_by_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'phone_number_clients',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('diff', models.CharField(default='', max_length=4096)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
            ],
            options={
                'db_table': 'phone_number_activities',
            },
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumberclient'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumberstatus'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
    ]
