# Generated by Django 4.2.9 on 2024-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_legal_mainphonenumber_phonenumber_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='note',
            field=models.CharField(default='', max_length=1048),
        ),
    ]
