# Generated by Django 4.2.9 on 2024-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_phonenumber_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_phone_number_management',
            field=models.BooleanField(default=False),
        ),
    ]
