# Generated by Django 4.2.9 on 2024-04-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_phonenumberactivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='client_use_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phonenumberclient'),
        ),
    ]
