# Generated by Django 4.2.9 on 2024-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_phonenumber_client_use_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='active_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='lock_history_id',
            field=models.IntegerField(default=0),
        ),
    ]
