# Generated by Django 4.2.9 on 2024-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_phonenumber_active_date_phonenumber_lock_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='distributor_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='lock_telco',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='number_in_distributor',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='number_left',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='proxy',
            field=models.CharField(default='', max_length=512),
        ),
    ]
