# Generated by Django 4.2.9 on 2024-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_phonenumber_distributor_name_phonenumber_lock_telco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('company', 'phone_number')},
        ),
    ]
