# Generated by Django 4.2.9 on 2024-04-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0070_alter_phonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='pic',
            field=models.ForeignKey(db_column='pic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
