# Generated by Django 4.2.9 on 2024-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_phonenumber_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberlockhistory',
            name='mobifone_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumberlockhistory',
            name='other_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumberlockhistory',
            name='viettel_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumberlockhistory',
            name='vinaphone_lock_date',
            field=models.DateField(null=True),
        ),
    ]
