# Generated by Django 4.2.9 on 2024-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_phonenumberlockhistory_mobifone_lock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='mobifone_lock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='mobifone_lock_history_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='other_lock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='other_lock_history_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='viettel_lock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='viettel_lock_history_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vinaphone_lock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vinaphone_lock_history_id',
            field=models.IntegerField(default=0),
        ),
    ]
