# Generated by Django 4.2.9 on 2024-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_phonenumber_mobifone_lock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='mobifone_unlocking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='mobifone_using_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='other_unlocking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='other_using_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='provider_cancel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='viettel_unlocking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='viettel_using_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vinaphone_unlocking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vinaphone_using_status',
            field=models.IntegerField(default=0),
        ),
    ]
