# Generated by Django 4.2.9 on 2024-05-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_phonenumber_mobifone_unlocking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='mobifone_unlocking_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='mobifone_using_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='other_unlocking_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='other_using_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='viettel_unlocking_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='viettel_using_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='vinaphone_unlocking_status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='vinaphone_using_status',
            field=models.CharField(default='', max_length=512),
        ),
    ]
