# Generated by Django 4.2.9 on 2024-05-30 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0075_alter_phonenumber_mobifone_unlocking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberTechnicalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('viettel_using_status', models.CharField(default='', max_length=512)),
                ('mobifone_using_status', models.CharField(default='', max_length=512)),
                ('vinaphone_using_status', models.CharField(default='', max_length=512)),
                ('other_using_status', models.CharField(default='', max_length=512)),
                ('viettel_unlocking_status', models.CharField(default='', max_length=512)),
                ('mobifone_unlocking_status', models.CharField(default='', max_length=512)),
                ('vinaphone_unlocking_status', models.CharField(default='', max_length=512)),
                ('other_unlocking_status', models.CharField(default='', max_length=512)),
                ('viettel_lock_date', models.DateField(null=True)),
                ('mobifone_lock_date', models.DateField(null=True)),
                ('vinaphone_lock_date', models.DateField(null=True)),
                ('other_lock_date', models.DateField(null=True)),
                ('viettel_unlock_date', models.DateField(null=True)),
                ('mobifone_unlock_date', models.DateField(null=True)),
                ('vinaphone_unlock_date', models.DateField(null=True)),
                ('other_unlock_date', models.DateField(null=True)),
                ('old_mobifone_using_status', models.CharField(default='', max_length=512)),
                ('old_vinaphone_using_status', models.CharField(default='', max_length=512)),
                ('old_other_using_status', models.CharField(default='', max_length=512)),
                ('old_viettel_unlocking_status', models.CharField(default='', max_length=512)),
                ('old_mobifone_unlocking_status', models.CharField(default='', max_length=512)),
                ('old_vinaphone_unlocking_status', models.CharField(default='', max_length=512)),
                ('old_other_unlocking_status', models.CharField(default='', max_length=512)),
                ('old_viettel_lock_date', models.DateField(null=True)),
                ('old_mobifone_lock_date', models.DateField(null=True)),
                ('old_vinaphone_lock_date', models.DateField(null=True)),
                ('old_other_lock_date', models.DateField(null=True)),
                ('old_viettel_unlock_date', models.DateField(null=True)),
                ('old_mobifone_unlock_date', models.DateField(null=True)),
                ('old_vinaphone_unlock_date', models.DateField(null=True)),
                ('old_other_unlock_date', models.DateField(null=True)),
                ('old_phone_number_status_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
                ('phone_number_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumberstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_number_technical_activities',
            },
        ),
    ]
