# Generated by Django 4.2.9 on 2024-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_phonenumbertechnicalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='last_technical_activity_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumbertechnicalactivity',
            name='old_viettel_using_status',
            field=models.CharField(default='', max_length=512),
        ),
    ]
