# Generated by Django 4.2.9 on 2024-06-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0077_phonenumber_last_technical_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberclient',
            name='pic',
            field=models.ForeignKey(db_column='pic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
