# Generated by Django 4.2.9 on 2024-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_phonenumberclient_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monthly_order_amount',
            field=models.FloatField(default=0),
        ),
    ]
