# Generated by Django 4.2.9 on 2024-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_order_monthly_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberlockhistory',
            name='send_provider_date',
            field=models.DateField(null=True),
        ),
    ]
