# Generated by Django 4.2.9 on 2024-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_phonenumberlockhistory_send_provider_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['product_id', 'deleted_at'], name='order_detail_product_idx'),
        ),
    ]
