# Generated by Django 4.2.9 on 2024-07-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_orderdetail_order_detail_product_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderdetail',
            name='order_detail_product_idx',
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['deleted_at', 'product_id'], name='od_product_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['product_id'], name='order_detail_product_idx'),
        ),
    ]
