# Generated by Django 4.2.9 on 2024-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_orderdetail_order_detail_product_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monthlyorderdetail',
            index=models.Index(fields=['month'], name='mod_month_idx'),
        ),
    ]
