# Generated by Django 4.2.9 on 2024-08-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_monthlyorderdetail_mod_month_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orderdetailpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_payments', to='api.payment'),
        ),
    ]
