# Generated by Django 4.2.9 on 2024-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_phonenumber_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='last_mobifone_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_mobifone_send_provider_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_mobifone_unlock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_other_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_other_send_provider_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_other_unlock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_viettel_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_viettel_send_provider_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_viettel_unlock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_vinaphone_lock_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_vinaphone_send_provider_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_vinaphone_unlock_date',
            field=models.DateField(null=True),
        ),
    ]
