# Generated by Django 4.2.9 on 2024-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_phonenumber_last_mobifone_lock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='device',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
