# Generated by Django 4.2.9 on 2024-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_phonenumber_device_phonenumber_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='callagent',
            name='tenant',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
