"""
Django settings for CRM project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import logging
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@d+t=4=)f3vj3n1yc6evrkrfb!r=59@p6$sm=y_u=tk5$_ya3w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed host
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.db.migrations',
    'django.contrib.messages',
    'rest_framework',
    'corsheaders',
    # Celery
    "django_celery_results",
    'drf_yasg',
    'groups_manager',
    'guardian',
    'api'
]

TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
},
]

# Middle ware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Root url
ROOT_URLCONF = 'crm.urls'

# WSGI
WSGI_APPLICATION = 'crm.wsgi.application'
ASGI_APPLICATION = 'crm.routing.application'

# Database
DATABASES = {
    # Server
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crm_db',
        'HOST': '115.146.123.8',
        'PORT': '3306',
        'USER': 'crm_be',
        'PASSWORD': '123456aA@',
    }
}

SILENCED_SYSTEM_CHECKS = ['mysql.E001']

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SWAGGER_SETTINGS = {
   'USE_SESSION_AUTH': False
}

# CORS_ORIGIN_WHITELIST = (
#     'https://115.75.188.163:5002'
# )

# Allow cors
# CORS_ORIGIN_ALLOW_ALL = True

# Allow header
from corsheaders.defaults import default_headers
# CORS_ALLOW_HEADERS = list(default_headers) + [
#     'token',
#     'Access-Control-Allow-Origin'

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',
    'http://localhost:8000',
    'http://115.146.123.8',
    'http://115.146.123.8:8000',
    'http://crm.ity.vn',
    'https://crm.ity.vn',
]
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://localhost:8000',
    'http://127.0.0.1:8080',
    'http://115.146.123.8',
    'http://115.146.123.8:8000',
    'http://crm.ity.vn',
    'https://crm.ity.vn',
    'https://115.146.123.8',
]

SESSION_COOKIE_SAMESITE = None
CRSF_COOKIE_SAMESITE = None

ALLOWED_HOSTS = ['115.146.123.8', 'localhost', '127.0.0.1', 'crm.ity.vn']

CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_HTTPONLY = False
# SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

# AUTH_USER_MODEL = 'models.CRMUser'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'api.common.exception.crm_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures'),
)

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic'
        }
    },
    'OPERATIONS_SORTER': 'method',
}


GROUPS_MANAGER = {
    # User and Groups sync settings
    'AUTH_MODELS_SYNC': True,
    'USER_USERNAME_PREFIX': '',
    'USER_USERNAME_SUFFIX': '',
    # Permissions
    'PERMISSIONS': {
        'owner': ['view', 'change', 'delete'],
        'group': ['view', 'change'],
        'groups_upstream': ['view'],
        'groups_downstream': [],
        'groups_siblings': ['view'],
    },
}

APPEND_SLASH=False

from datetime import timedelta


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(weeks=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

CORS_ALLOW_HEADERS = ('content-disposition', 'accept-encoding',
                      'content-type', 'accept', 'origin', 'authorization', 'token')

CRAWLER_REDIRECT_URI = 'https://crm.ity.vn'

FB_APP_ID = '318537180209438'
FB_APP_SECRET = 'c091a3a9b59e1475abc049f9b352cc72' 
REDIRECT_URI = 'https://crm.ity.vn/api/fb/login/callback'
FB_SCOPE = 'pages_show_list,pages_messaging,pages_read_engagement,pages_read_user_content'
FB_IV = '1219164814273683'
FB_SECRET_KEY = '1381444214459712'

ZALO_APP_ID = '2252452034861651725'
ZALO_APP_SECRET = 'mNC5uCK6TN6kBgD5oqU6'
ZALO_SECRET_KEY = 'c091a3a9b59e1475abc049f9b352cc72' 
ZALO_REDIRECT_URI = 'https://crm.ity.vn/api/zalo/login/callback'

LOG_ROOT = '/var/log/crm/'
LOG_LEVEL = logging.DEBUG

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://{0}:{1}'.format(REDIS_HOST, REDIS_PORT)
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"

