"""
Django settings for CRM project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@d+t=4=)f3vj3n1yc6evrkrfb!r=59@p6$sm=y_u=tk5$_ya3w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed host
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.db.migrations',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'api',
    'aim.apps.asset',
    'aim.apps.trading',
    'aim.apps.accounting',
    'aim.apps.user',
    'aim.apps.address'
    # 'aim.apps.menu_web'
]

TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
},
]

# Middle ware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware'
]

# Root url
ROOT_URLCONF = 'aim.urls'

# WSGI
WSGI_APPLICATION = 'aim.wsgi.application'
ASGI_APPLICATION = 'aim.routing.application'

# Database
DATABASES = {
    # Server
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'aim',
        'USER': 'postgres',
        'PASSWORD': 'inet@123',
        'HOST': '14.225.7.229',
        'PORT': '5432',
    }

    # Local
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'order_way',
    #     'USER': 'postgres',
    #     'PASSWORD': 'thaico7762160',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
}


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_L10N = True
USE_TZ = False

STATIC_URL = '/static/'
SWAGGER_SETTINGS = {
   'USE_SESSION_AUTH': False
}

# CORS_ORIGIN_WHITELIST = (
#     'https://115.75.188.163:5002'
# )

# Allow cors
CORS_ORIGIN_ALLOW_ALL = True

# Allow header
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'token',
    'Access-Control-Allow-Origin'
]