"""
Definition of Const.
"""


class Const:
    # Secret key
    SECRET_KEY = "Y@1Z!F5Q!W6D!@K7ZS##0MR*&6N@#R4R$!P1EN3X!C8&&EB"

    # Role admin system
    ROLE_ADMIN_SYSTEM = "ADMIN"

    # Group admin system
    GROUP_ADMIN_SYSTEM = "ADMIN"

    # File path
    FILE_ROOT = "files/"

    # Sip server
    SIP_SERVER = "wss://vnsale.siptrunk.vn:58089/ws"

    FB_TIME_FORMAT = '%Y-%m-%dT%H:%M:%S%z'


class ASSET_STATUS:
    NEW = 'NEW'
    CLOSED = 'CLOSED'
    OWNING = 'OWNING'


class MODULES:
    COMPANY_MANAGEMENT = 'COMPANY_MANAGEMENT'
    ADMIN_MANAGEMENT = 'ADMIN_MANAGEMENT'
    USER_MANAGEMENT = 'USER_MANAGEMENT'
    MARKETING = 'MARKETING'
    DATA_MANAGEMENT = 'DATA_MANAGEMENT'
    DATA_MANAGEMENT_FOR_SALE = 'DATA_MANAGEMENT_FOR_SALE'
    PRODUCT_AND_WAREHOUSE = 'PRODUCT_AND_WAREHOUSE'
    CALL_CENTER_MANAGEMENT = 'CALL_CENTER_MANAGEMENT'
    CALL_CENTER_LIST_MANAGEMENT = 'CALL_CENTER_LIST_MANAGEMENT'
    CALL_CENTER_ABOUT = 'CALL_CENTER_ABOUT'
    ACCOUNTING = 'ACCOUNTING'
    SYSTEM_CONFIGURATION = 'SYSTEM_CONFIGURATION'
    REPORT = 'REPORT'
    PARAM_CONFIG = 'PARAM_CONFIG'
    SYNC_SOCIAL_NETWORK = 'SYNC_SOCIAL_NETWORK'
    USER_CALL_CENTER_MANAGEMENT = 'USER_CALL_CENTER_MANAGEMENT'


class CALL_DIRECTION:
    INCOMING = 'incoming'
    OUTGOING = 'outgoing'


class TELECOM_NUMBER:
    VIETTEL = 'VIETTEL'
    MOBI = 'MOBIFONE'
    VINA = 'VINAPHONE'
    OTHER = 'OTHER'


class PAYMENT_STATUS:
    PAID = 'PAID'
    UNPAID = 'UNPAID'


class DISCOUNT_TYPE:
    PERCENT = 'PERCENT'
    VALUE = 'VALUE'


class CALL_AGENT_STATUS:
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class ORDER_DETAIL_TYPE:
    NEW_BUY = 'NEW_BUY'
    ANNUAL_BUY = 'ANNUAL_BUY'


class DEBT_STATUS:
    NOTIFIED = 'NOTIFIED'
    UNPAID = 'UNPAID'
    UNAPPROVED = 'UNAPPROVED'
    APPROVED = 'APPROVED'


class PRODUCT_PAYMENT_METHOD:
    CREDIT = 'CREDIT'
    DEBIT = 'DEBIT'


class ORDER_PAYMENT_STATUS:
    WAITING_APPROVAL = 'WAITING_APPROVAL'
    APPROVED = 'APPROVED'
    DISAPPROVED = 'DISAPPROVED'
    CANCELLED = 'CANCELLED'
    DELETED = 'DELETED'


class PAYMENT_METHOD:
    CASH = 'CASH'
    CARD = 'CARD'
    TRANSFER = 'TRANSFER'


class NOTIFICATION_TYPE:
    DEBT = 'DEBT'
    RENEW = 'RENEW'
    ANNUAL_BUY = 'ANNUAL_BUY'
    NEW_PAYMENT = 'NEW_PAYMENT'
    APPROVE_PAYMENT = 'APPROVE_PAYMENT'
    UNAPPROVE_PAYMENT = 'UNAPPROVE_PAYMENT'
    DEPOSIT_THRESOLD = 'DEPOSIT_THRESOLD'


class PARAM_KEY:
    GENERAL_PACKAGE = 'GENERAL_PACKAGE'

class PRICE_TYPE:
    VIETTEL = 'viettel'
    VINAPHONE = 'vinaphone'
    MOBIFONE = 'mobifone'
    OTHER = 'other'

class CALL_CENTER_PAYMENT_METHOD:
    CREDIT = 'CREDIT'
    DEBIT = 'DEBIT'


class CALL_CENTER_CHARGE_METHOD:
    MINUTE = 'MINUTE'
    AGENT = 'AGENT'


class CACHE_KEY:
    COMPANY_EXTENSION = 'company_extension'
    CALL_CENTER_MINUTE = 'call_center_minute'
    GENERAL_PACKAGE = 'general_package'
    PACKAGE = 'package'
